apiVersion: v1
kind: Secret
metadata:
  name: emergency-connect-secrets
  namespace: emergency-connect
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "rootpassword"
  REDIS_PASSWORD: "ecpassword"
  JWT_SECRET: "dev-secret-key-for-local-development-only-must-be-256-bits"
  MAIL_USERNAME: "csc406.yohannis.1093892@gmail.com"
  MAIL_PASSWORD: "zebfdooppemszzaj"