/**
 * CSC408 - Spring 2026
 * Section: 104 | Group: 6
 * Members: Yohannis-1093892, Indalu-1093915, Biniam-1093887
 */
package com.emergencyconnect.audit.controller;

import com.emergencyconnect.audit.dto.ChainVerificationResult;
import com.emergencyconnect.audit.dto.EntryVerificationResult;
import com.emergencyconnect.audit.dto.MerkleCommitResult;
import com.emergencyconnect.audit.model.AuditLog;
import com.emergencyconnect.audit.model.MerkleRoot;
import com.emergencyconnect.audit.repository.MerkleRootRepository;
import com.emergencyconnect.audit.service.AuditService;
import com.emergencyconnect.audit.service.IntegrityVerificationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/audit")
@RequiredArgsConstructor
@Tag(name = "Audit Logs", description = "Query tamper-evident audit logs for compliance and incident review")
@SecurityRequirement(name = "bearerAuth")
public class AuditController {

    private final AuditService auditService;
    private final IntegrityVerificationService integrityService;
    private final MerkleRootRepository merkleRootRepository;

    @GetMapping("/logs")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "List audit logs",
               description = "Paginated, filterable list of all system audit events. Supports filtering by event type and time range. ADMIN only.")
    @ApiResponse(responseCode = "200", description = "Audit logs returned")
    public ResponseEntity<Page<AuditLog>> getLogs(
            @Parameter(description = "Filter by event type, e.g. LOGIN_SUCCESS") @RequestParam(required = false) String eventType,
            @Parameter(description = "Start of time range (ISO-8601)") @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant from,
            @Parameter(description = "End of time range (ISO-8601)") @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant to,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {
        return ResponseEntity.ok(auditService.getLogs(eventType, from, to, PageRequest.of(page, size)));
    }

    @GetMapping("/logs/incident/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs for an incident",
               description = "Returns all audit events linked to a specific incident UUID. ADMIN only.")
    @ApiResponse(responseCode = "200", description = "Incident audit trail returned")
    public ResponseEntity<Page<AuditLog>> getByIncident(
            @Parameter(description = "Incident UUID") @PathVariable UUID id,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {
        return ResponseEntity.ok(auditService.getLogsByIncident(id, PageRequest.of(page, size)));
    }

    @GetMapping("/logs/user/{userId}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Get audit logs for a user",
               description = "Returns all audit events generated by a specific user UUID. ADMIN only.")
    @ApiResponse(responseCode = "200", description = "User audit trail returned")
    public ResponseEntity<Page<AuditLog>> getByUser(
            @Parameter(description = "User UUID") @PathVariable UUID userId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {
        return ResponseEntity.ok(auditService.getLogsByUser(userId, PageRequest.of(page, size)));
    }

    @GetMapping("/dashboard")
    @Operation(summary = "Audit dashboard summary",
               description = "Returns event-type counts for the real-time WebSocket audit dashboard.")
    @ApiResponse(responseCode = "200", description = "Summary counts returned")
    public ResponseEntity<Map<String, Long>> getDashboard() {
        return ResponseEntity.ok(auditService.getDashboardSummary());
    }

    @GetMapping("/integrity/verify/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Verify single audit entry",
               description = "Re-computes the SHA-256 hash of the entry and compares it against the stored hash. " +
                             "A mismatch means the record was modified after it was written.")
    @ApiResponse(responseCode = "200", description = "Verification result returned")
    public ResponseEntity<EntryVerificationResult> verifyEntry(
            @Parameter(description = "Audit log UUID") @PathVariable UUID id) {
        return ResponseEntity.ok(integrityService.verifyEntry(id));
    }

    @GetMapping("/integrity/verify-chain")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Verify hash chain integrity",
               description = "Verifies the full SHA-256 hash chain for the most recent N entries. " +
                             "Any modification to a historical record breaks all subsequent hashes.")
    @ApiResponse(responseCode = "200", description = "Chain verification result returned")
    public ResponseEntity<ChainVerificationResult> verifyChain(
            @Parameter(description = "Number of recent entries to verify (default 100)")
            @RequestParam(defaultValue = "100") int limit) {
        return ResponseEntity.ok(integrityService.verifyChain(limit));
    }

    @PostMapping("/integrity/commit-merkle")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Commit a Merkle root",
               description = "Builds a binary Merkle tree from the most recent N audit entries and stores the root hash. " +
                             "Individual entries can later be verified against this root in O(log n) time.")
    @ApiResponse(responseCode = "200", description = "Merkle root committed and stored")
    public ResponseEntity<MerkleCommitResult> commitMerkle(
            @Parameter(description = "Number of entries to include in this batch (default 100)")
            @RequestParam(defaultValue = "100") int limit) {
        return ResponseEntity.ok(integrityService.commitMerkleRoot(limit));
    }

    @GetMapping("/integrity/merkle-roots")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "List committed Merkle roots",
               description = "Returns the history of committed Merkle roots, most recent first. Each root is a cryptographic " +
                             "commitment to a batch of audit entries and can be used to verify individual inclusions.")
    @ApiResponse(responseCode = "200", description = "Merkle roots returned")
    public ResponseEntity<Page<MerkleRoot>> getMerkleRoots(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        return ResponseEntity.ok(merkleRootRepository.findAllByOrderByCommittedAtDesc(PageRequest.of(page, size)));
    }
}
